name: 'Build with Apache Maven'

description: Build with Apache Maven

inputs:
  setup-java-token:
    description: The token used to authenticate when fetching version manifests hosted on github.com, such as for the Microsoft Build of OpenJDK. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
runs:

  using: 'composite'

  steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - run: mvn package
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.setup-java-token }}
