name: 'Build with Apache Maven'

description: Build with Apache Maven

inputs:
  setup-java-server-id:
    description: 'github'
    required: true
  setup-java-server-username:
    description: 'github.actor'
    required: true
  setup-java-server-password:
    description: 'secrets.GITHUB_TOKEN'
    required: true
    
runs:

  using: 'composite'

  steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
        server-id: ${{ inputs.setup-java-server-id }}
        server-username: ${{ inputs.setup-java-server-username }}
        server-password: ${{ inputs.setup-java-server-password }}

    - run: mvn clean install

    - run: mvn test
